name: Node CI-CD

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read  # <--- allows to read repo

jobs:
  build-and-deploy-to-gh-pages:
    name: Build and Deploy to GitHub Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          
      - name: Install and Build
        run: npm ci
        run: npm run build
      
      - name:  Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.0
        with:
          token: ${{secrets.ACCESS_TOKEN}}
          branch: gh-pages
          folder: dist
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ll-to-address
          path: dist
          
  deploy_to_my_blog:
    name: Deploy to My Blog
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v3
        with:
          name: ll-to-address
          path: dist
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          ARGS: '-avzr --delete'
          SOURCE: 'dist/'
          TARGET: ${{ secrets.REMOTE_TARGET }}